os: windows

language: node_js
node_js:
  - 'node'

script:
  # - yarn cypress install
  # - yarn test
  - yarn build
cache:
  yarn: true
  directories:
    - ~/.cache
deploy:
  provider: pages
  target_branch: master
  local_dir: public
  skip_cleanup: true
  github_token: $DEPLOY_TOKEN
  keep_history: true
  on:
    branch: dev
